[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "bc8c2d70256618b73aac6655e9d88bce384df4bb"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "6b4765d1d2c83232a3d568ed8d13110436508e6a372ea34606ae1d565441150c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.aarch64-linux-musl.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcf9d29b62f40e2ab05e627ba2bacada90b98bd0"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "93598fe3490d65e1f5c1015ae4be87f3d44cd35d28c3fb09e72c66e5cbae7535"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv6l-linux-gnueabihf.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b22269b5ceb0be6a966082c35f6a7dda533b94f4"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "bb904bd08bf58cf624337e24dee899470482d019ce2ac1ec6db5fdd726954482"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv6l-linux-musleabihf.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d7434468f75a8cb0e827cc4d590b83194c571580"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "57582964a731baa8ae669a6a8f0182e6f93ef45b1edc4bf7a1b698540369ba59"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv7l-linux-gnueabihf.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc45b7a48e780005ec33cdad8893c5559e040801"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "f8ccb9f7363b36a254d97e4e5bb0b035927a2fef8d71863ffbb64a8b4e94c15c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv7l-linux-musleabihf.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "d4cba0704dda96df46229fb578f0c28f12a6b71e"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "9dc52a18bc9cdc6b9d2174fbccccce833a2c1504035cf216ddccedb9e1d4cb24"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.i686-linux-gnu.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "e6c39e8b06fcf6f530d22d4a97eb86baa17af1c7"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "d0997a61480eb269cc3561489aea523421be4ad70719bdadae1564df958b45e3"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.i686-linux-musl.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "510fd58d925c3793953d789a2899c661078918f7"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "0ff0c47993702edffbaeccfb7a6a2bc8254338fe19310fa7f19ff6cc0fd62ae2"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.powerpc64le-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "272611f9064ffaf322a682f5c1c7d2a52d8dd39c"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "8bae79a1fbb18af927aa670bd927a95526bdd38d7f8a8fcebe36aa94a065985a"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.x86_64-linux-musl.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "97d162e27d3c3194f7aa00eb829d23074c89da4f"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "653ee57d5d72ae799fbdb6d1b5c80a26e70ee09c7db0b296cc7b4f999bc724a0"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.x86_64-unknown-freebsd.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "cce5f422c402d49e2eaaf6fbaaf0872e24808d70"
lazy = true
os = "macos"

    [[NetCDF.download]]
    sha256 = "0f4efa929dcc11715fee818753bdee766899af71776d541353addebfa0d08b0e"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+1/NetCDF.v401.900.300.aarch64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "df4d12d028682ebb02e55e7839ef1e9736fde587"
lazy = true
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "a2e3856c0a645a3d93c5e9025cee77c0544f8b1f5f04f203d147994edaaea432"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+1/NetCDF.v401.900.300.aarch64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "0311a1aa9f45b2143d8389aca9657ba4d054a481"
lazy = true
os = "windows"

    [[NetCDF.download]]
    sha256 = "27298794efd7a44954fdf42e50978e8df536538bbb0b6b8f4cb2569b03cb8c86"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+1/NetCDF.v401.900.300.i686-w64-mingw32.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "41df64d9668b0d047005e473e69aca4e1a6c4698"
lazy = true
os = "macos"

    [[NetCDF.download]]
    sha256 = "2741c3c3abafd8584a35fbf3dbd381ca1f1efd32cc3e2ab09f86a2bb267e2651"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+1/NetCDF.v401.900.300.x86_64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "4f9e9401626618e7cac18b81ee376e995ea66980"
lazy = true
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "974cdcfdc2b9456d99daa16295fcf1da31304a7c2ed4c778d52f46bb5256d40d"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+1/NetCDF.v401.900.300.x86_64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "296aa9891b9aa5b28e5de9c604d1764980f66171"
lazy = true
os = "windows"

    [[NetCDF.download]]
    sha256 = "ebe10853d13df19c74df94e2a8c8d1e42c617278671b9aab35204101242ae75e"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v401.900.300+1/NetCDF.v401.900.300.x86_64-w64-mingw32.tar.gz"
