[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "bc8c2d70256618b73aac6655e9d88bce384df4bb"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "6b4765d1d2c83232a3d568ed8d13110436508e6a372ea34606ae1d565441150c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.aarch64-linux-musl.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fcf9d29b62f40e2ab05e627ba2bacada90b98bd0"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "93598fe3490d65e1f5c1015ae4be87f3d44cd35d28c3fb09e72c66e5cbae7535"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv6l-linux-gnueabihf.tar.gz"
[[NetCDF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b22269b5ceb0be6a966082c35f6a7dda533b94f4"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "bb904bd08bf58cf624337e24dee899470482d019ce2ac1ec6db5fdd726954482"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv6l-linux-musleabihf.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d7434468f75a8cb0e827cc4d590b83194c571580"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "57582964a731baa8ae669a6a8f0182e6f93ef45b1edc4bf7a1b698540369ba59"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv7l-linux-gnueabihf.tar.gz"
[[NetCDF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc45b7a48e780005ec33cdad8893c5559e040801"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "f8ccb9f7363b36a254d97e4e5bb0b035927a2fef8d71863ffbb64a8b4e94c15c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.armv7l-linux-musleabihf.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "d4cba0704dda96df46229fb578f0c28f12a6b71e"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "9dc52a18bc9cdc6b9d2174fbccccce833a2c1504035cf216ddccedb9e1d4cb24"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.i686-linux-gnu.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "e6c39e8b06fcf6f530d22d4a97eb86baa17af1c7"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "d0997a61480eb269cc3561489aea523421be4ad70719bdadae1564df958b45e3"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.i686-linux-musl.tar.gz"
[[NetCDF]]
arch = "powerpc64le"
git-tree-sha1 = "510fd58d925c3793953d789a2899c661078918f7"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "0ff0c47993702edffbaeccfb7a6a2bc8254338fe19310fa7f19ff6cc0fd62ae2"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.powerpc64le-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "272611f9064ffaf322a682f5c1c7d2a52d8dd39c"
libc = "musl"
os = "linux"

    [[NetCDF.download]]
    sha256 = "8bae79a1fbb18af927aa670bd927a95526bdd38d7f8a8fcebe36aa94a065985a"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.x86_64-linux-musl.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "97d162e27d3c3194f7aa00eb829d23074c89da4f"
os = "freebsd"

    [[NetCDF.download]]
    sha256 = "653ee57d5d72ae799fbdb6d1b5c80a26e70ee09c7db0b296cc7b4f999bc724a0"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.239+0/NetCDF.v400.902.239.x86_64-unknown-freebsd.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "f2f4da661a3ca70c34ba7f41b03d338ee154a922"
os = "macos"

    [[NetCDF.download]]
    sha256 = "b81d81e79ce8eb5cf271c46e435e8beef665f93f7bfe747c529b4c4ae28e9a5c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.241+0/NetCDF.v400.902.241.aarch64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "aarch64"
git-tree-sha1 = "77d1352cdf0d30c80565b1fe4d17e832067cfd04"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "9c64055a3c0276c92b4d6f52a9e6e0dd7529d72bd6234b253045ac3791b27cf3"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.241+0/NetCDF.v400.902.241.aarch64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "i686"
git-tree-sha1 = "9c72cd2ba313b7e9173108d1e167394a299450b8"
os = "windows"

    [[NetCDF.download]]
    sha256 = "06d210c7cd913c647ab77760d2656f88e9fd8e9c55dabe9058365a7855b35c7c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.241+0/NetCDF.v400.902.241.i686-w64-mingw32.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "ce06e8e0e6d4c35585e4c5cc612f0616ae24bb96"
os = "macos"

    [[NetCDF.download]]
    sha256 = "8f8dc75dc6daf3798eb01acb2a22214b4465c04fe2861aabbeaf31901c61d8ad"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.241+0/NetCDF.v400.902.241.x86_64-apple-darwin.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "39b906c6f6ce961b52924699da29a8c6189ceae6"
libc = "glibc"
os = "linux"

    [[NetCDF.download]]
    sha256 = "b73c9bc46bf86d11e31832ce4bfdb17deb12dc869f29a4bad551d8a559b65f82"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.241+0/NetCDF.v400.902.241.x86_64-linux-gnu.tar.gz"
[[NetCDF]]
arch = "x86_64"
git-tree-sha1 = "9e587c92993da9a5948f17e44eb184c7ba8f979f"
os = "windows"

    [[NetCDF.download]]
    sha256 = "fd5fdf6cbe3f4a6a3942187843cbfd8077620cbb94d20a24e7ffeb9a82d4504c"
    url = "https://github.com/Alexander-Barth/NetCDF_jll.jl/releases/download/NetCDF-v400.902.241+0/NetCDF.v400.902.241.x86_64-w64-mingw32.tar.gz"
