# Autogenerated wrapper script for NetCDF_jll for x86_64-linux-gnu
export lib__nch5blosc, lib__nch5bzip2, lib__nch5deflate, lib__nch5fletcher32, lib__nch5shuffle, lib__nch5szip, lib__nch5zstd, lib__nczhdf5filters, lib__nczstdfilters, libnetcdf, nc4print, nccopy, ncdump, ncgen, ncgen3, ocprint

using Blosc_jll
using Bzip2_jll
using HDF5_jll
using LibCURL_jll
using XML2_jll
using Zlib_jll
using Zstd_jll
using libaec_jll
using libzip_jll
using MPIABI_jll
using MPICH_jll
using MPItrampoline_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("NetCDF")
JLLWrappers.@declare_library_product(lib__nch5blosc, "lib__nch5blosc.so")
JLLWrappers.@declare_library_product(lib__nch5bzip2, "lib__nch5bzip2.so")
JLLWrappers.@declare_library_product(lib__nch5deflate, "lib__nch5deflate.so")
JLLWrappers.@declare_library_product(lib__nch5fletcher32, "lib__nch5fletcher32.so")
JLLWrappers.@declare_library_product(lib__nch5shuffle, "lib__nch5shuffle.so")
JLLWrappers.@declare_library_product(lib__nch5szip, "lib__nch5szip.so")
JLLWrappers.@declare_library_product(lib__nch5zstd, "lib__nch5zstd.so")
JLLWrappers.@declare_library_product(lib__nczhdf5filters, "lib__nczhdf5filters.so")
JLLWrappers.@declare_library_product(lib__nczstdfilters, "lib__nczstdfilters.so")
JLLWrappers.@declare_library_product(libnetcdf, "libnetcdf.so.22")
JLLWrappers.@declare_executable_product(nc4print)
JLLWrappers.@declare_executable_product(nccopy)
JLLWrappers.@declare_executable_product(ncdump)
JLLWrappers.@declare_executable_product(ncgen)
JLLWrappers.@declare_executable_product(ncgen3)
JLLWrappers.@declare_executable_product(ocprint)
function __init__()
    JLLWrappers.@generate_init_header(Blosc_jll, Bzip2_jll, HDF5_jll, LibCURL_jll, XML2_jll, Zlib_jll, Zstd_jll, libaec_jll, libzip_jll, MPIABI_jll, MPICH_jll, MPItrampoline_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        lib__nch5blosc,
        "hdf5/lib/plugin/lib__nch5blosc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nch5bzip2,
        "hdf5/lib/plugin/lib__nch5bzip2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nch5deflate,
        "hdf5/lib/plugin/lib__nch5deflate.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nch5fletcher32,
        "hdf5/lib/plugin/lib__nch5fletcher32.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nch5shuffle,
        "hdf5/lib/plugin/lib__nch5shuffle.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nch5szip,
        "hdf5/lib/plugin/lib__nch5szip.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nch5zstd,
        "hdf5/lib/plugin/lib__nch5zstd.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nczhdf5filters,
        "hdf5/lib/plugin/lib__nczhdf5filters.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib__nczstdfilters,
        "hdf5/lib/plugin/lib__nczstdfilters.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnetcdf,
        "lib/libnetcdf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nc4print,
        "bin/nc4print",
    )

    JLLWrappers.@init_executable_product(
        nccopy,
        "bin/nccopy",
    )

    JLLWrappers.@init_executable_product(
        ncdump,
        "bin/ncdump",
    )

    JLLWrappers.@init_executable_product(
        ncgen,
        "bin/ncgen",
    )

    JLLWrappers.@init_executable_product(
        ncgen3,
        "bin/ncgen3",
    )

    JLLWrappers.@init_executable_product(
        ocprint,
        "bin/ocprint",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
